// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE
'use strict';

var Axios = require("axios");

function getProjectDetails(projectId, token) {
  return Axios.get("https://gitlab.com/api/v4/projects/" + (projectId + ("?private_token=" + token))).then((function (response) {
                return Promise.resolve(response.data);
              }));
}

exports.getProjectDetails = getProjectDetails;
/* axios Not a pure module */
