// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE
'use strict';

var $$Array = require("bs-platform/lib/js/array.js");
var Axios = require("axios");
var Js_dict = require("bs-platform/lib/js/js_dict.js");

var url = "https://gitlab.com/api/v4/projects/";

function getProjectDetails(projectId, token) {
  return Axios.get(url + (projectId + ("?private_token=" + token))).then((function (response) {
                return Promise.resolve(response.data);
              }));
}

function getMergeRequestDetails(projectId, token, mergeRequestId) {
  return Axios.get(url + (projectId + ("/merge_requests/" + (mergeRequestId + ("?private_token=" + token))))).then((function (response) {
                return Promise.resolve(response.data);
              }));
}

function fetchProjects(projectIds, token) {
  return Promise.all($$Array.map((function (projectId) {
                      return getProjectDetails(projectId, token);
                    }), projectIds)).then((function (projects) {
                return Promise.resolve(Js_dict.fromArray($$Array.map((function (project) {
                                      return /* tuple */[
                                              project.id,
                                              project
                                            ];
                                    }), projects)));
              }));
}

exports.url = url;
exports.getProjectDetails = getProjectDetails;
exports.getMergeRequestDetails = getMergeRequestDetails;
exports.fetchProjects = fetchProjects;
/* axios Not a pure module */
