// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE
'use strict';

var Js_mapperRt = require("bs-platform/lib/js/js_mapperRt.js");

var jsMapperConstantArray = /* array */[
  /* tuple */[
    -641268470,
    "locked"
  ],
  /* tuple */[
    134725292,
    "merged"
  ],
  /* tuple */[
    240232876,
    "closed"
  ],
  /* tuple */[
    563372713,
    "opened"
  ]
];

function mergeRequestStateToJs(param) {
  return Js_mapperRt.binarySearch(4, param, jsMapperConstantArray);
}

function mergeRequestStateFromJs(param) {
  return Js_mapperRt.revSearch(4, jsMapperConstantArray, param);
}

exports.mergeRequestStateToJs = mergeRequestStateToJs;
exports.mergeRequestStateFromJs = mergeRequestStateFromJs;
/* No side effect */
